name: Get Recently Played Tracks

on:
  workflow_dispatch:
  schedule:
    - cron: '4 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: pip
    - name: Install python dependencies
      run: |-
        pip install -r requirements.txt
        playwright install chromium
    - name: Get tracks played in the last hour
      run: |-
        python app.py get-recently-played after "$(date -v-1H +"%Y-%m-%d %T")" --limit 50 --time-zone UTC --write --filename recently_played.json
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_AUTH_STRING: ${{ secrets.SPOTIFY_AUTH_STRING }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
    - name: Commit and push if it changed 
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push