name: Get Recently Played Tracks

on:
  workflow_dispatch:
  schedule:
    - cron: '13 * * * *'

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: pip
    - name: Cache Spotify info
      uses: actions/cache@v5
      with:
        path: ~/.config/esporifai/
        key: ${{ runner.os }}-esporifai-v2
    - name: Install python dependencies
      run: |-
        pip install -r requirements.txt
    - name: Ensure Spotify auth
      run: |
        esporifai auth --status
        esporifai auth --force
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_AUTH_STRING: ${{ secrets.SPOTIFY_AUTH_STRING }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
    - name: Get tracks played in the last hour
      run: |-
        timestamp="$(jq -r '.cursors | if (.after) then (.after|tonumber/1000 | strftime("%Y-%m-%d %T")) else null end' data/recently_played.json)"
        if [ -z "$timestamp" ] || [ "$timestamp" = "null" ]; then
          timestamp="$(date -d "1 hour ago" +'%Y-%m-%d %T')"
        fi
        echo "$timestamp"
        esporifai get-recently-played after \
        "$timestamp" \
        --limit 50 \
        --time-zone UTC \
        --output data/recently_played.json
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_AUTH_STRING: ${{ secrets.SPOTIFY_AUTH_STRING }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
    - name: Clean up items using jq
      run: |-
        cat data/recently_played.json | jq {items} > data/recently_played_items.json
    - name: Commit and push if it changed 
      run: |-
        git pull
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
